### ISSUE TITLE
Only python 3 code. 

### ISSUE THREAD

**Issue by reliefs** [instagrambot/Instagram-scraper-with-autopost#4]
Somehow i got stuck in the loop, I do not know the syntax difference between python2 and python3. People report issues, that there are some mixed python 2 and python 3 syntax. 

Should be easy to fix. 

Some feedback:
> You're passing the result of somedict.keys() to the function. In Python 3, dict.keys doesn't return a list, but a set-like object that represents a view of the dictionary's keys and (being set-like) doesn't support indexing.....

**Comment by reliefs** [comment]
More data about the error on a clean Ubuntu Install:

`Traceback (most recent call last):
  File "example.py", line 280, in <module>
    instascraper(bot, users, args.amount)
  File "example.py", line 155, in instascraper
    InstaImageScraper()
  File "example.py", line 127, in InstaImageScraper
    imgScraper.scrape()
  File "/usr/local/lib/python3.6/dist-packages/instagram_scraper/app.py", line 666, in scrape
    self.merge_json({ 'GraphImages': self.posts }, '{0}/{1}.json'.format(dst, username))
  File "/usr/local/lib/python3.6/dist-packages/instagram_scraper/app.py", line 1155, in merge_json
    key = merged.keys()[0]
TypeError: 'dict_keys' object does not support indexing
2019-04-08 23:36:31,470 - INFO - Bot stopped. Worked: 0:00:11.535895
2019-04-08 23:36:31,471 - INFO - Total requests: 6`

**Comment by reliefs** [comment]
Issue located it's inside instagram-scraper module
https://github.com/rarcega/instagram-scraper/issues/359
