### ISSUE TITLE
not reposting 

### ISSUE THREAD

**Issue by Banginpadr** [instagrambot/Instagram-scraper-with-autopost#5]
04-10 01:19:15,363 - INFO - Instabot Started
2019-04-10 01:19:16,379 - INFO - Logged-in successfully as 'fit_nation'!
2019-04-10 01:19:17,743 - INFO - Stats saved at 2019-04-10 01:19:17.
Searching taneth.fit for profile pic: 100% 1/1 [00:00<00:00, 732.50 images/s]
Searching taneth.fit for posts: 0 media [00:00, ? media/s]
Downloading: 100%|##########| 1/1 [00:00<00:00, 4999.17it/s]
image scraping is running or not
image set to private taneth.fit
Searching fitfemalesclub for profile pic: 100% 1/1 [00:00<00:00, 1364.45 images/s]
Searching fitfemalesclub for posts: 0 media [00:00, ? media/image scraping is running or not
image set to private fitfemalesclub00:00<00:00, 6853.44it/s]
                                                            image scraping is running or not
image set to private xkimpossible90x0:00<00:00, 6944.21it/s]/s]0, 1618.17 images/s]
Traceback (most recent call last):
  File "example.py", line 167, in instascraper
    newstr = (json_data[0]["display_url"])
KeyError: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "example.py", line 167, in instascraper
    newstr = (json_data[0]["display_url"])
KeyError: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "example.py", line 167, in instascraper
    newstr = (json_data[0]["display_url"])
KeyError: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "example.py", line 281, in <module>
    instascraper(bot, users, args.amount)
  File "example.py", line 260, in instascraper
    instascraper(bot, new_media_id, path=POSTED_MEDIAS)
  File "example.py", line 260, in instascraper
    instascraper(bot, new_media_id, path=POSTED_MEDIAS)
  File "example.py", line 260, in instascraper
    instascraper(bot, new_media_id, path=POSTED_MEDIAS)
  File "example.py", line 156, in instascraper
    InstaImageScraper()
  File "example.py", line 124, in InstaImageScraper
    imgScraper = insta.InstagramScraper(usernames=[insta_profiles[x]],
IndexError: list index out of range

2019-04-10 01:20:01,224 - INFO - Bot stopped. Worked: 1 day, 23:36:26.707512
2019-04-10 01:20:01,226 - INFO - Total requests: 36

when i run the program this is the error i get. it doesnt post nothing. it just download some fotos to the file in my pc but it wont make post in my ig

**Comment by reliefs** [comment]
should be fixed now can you try to update ?

**Comment by Banginpadr** [comment]
> should be fixed now, can you try to update ?

you have to commit it first for me to pull it
